### ISSUE TITLE
Random episode not working (southpark.cc.com moved to https)

### ISSUE THREAD

**Issue by mvn23** [wargio/plugin.video.southpark_unofficial#14]
When trying to play a random episode, I get the message that an error has occured and I should check the logs. In the logs, I get the following message:
```
2019-07-16 20:27:54.404 T:140618587281152   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/home/mvn23/.kodi/addons/plugin.video.southpark_unofficial/default.py", line 9, in <module>
                                                plugin.handle()
                                              File "/home/mvn23/.kodi/addons/plugin.video.southpark_unofficial/southpark.py", line 583, in handle
                                                self.create_random()
                                              File "/home/mvn23/.kodi/addons/plugin.video.southpark_unofficial/southpark.py", line 344, in create_random
                                                rand = rand.split(self.helper.random_episode("s"))[1].split("-")[0].split("e")
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
2019-07-16 20:27:54.462 T:140621116136128   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.southpark_unofficial/?url=&mode=sp:random&title=Random Episode&thumbnail=/home/mvn23/.kodi/addons/plugin.video.southpark_unofficial/icon.png]
```

I traced this down to a `301 - Moved Permanently` response from the server upon requesting the initial page from `http://southpark.cc.com/full-episodes/random`. This request is redirected to `https://southpark.cc.com/full-episodes/random` and the resulting page gives the link to the actual episode (obtained in line 341 of southpark.py) also with an `https` prefix.
Due to the fact that `rand` now contains the `https` url and `self.helper.random_episode("s")` returns the `http` url, `rand.split(self.helper.random_episode("s"))` on line 342 will only contain 1 element. When we then try to access element `[1]`, we get the IndexError.

I have managed to fix this quickly by changing the url pattern on line 257 of southpark.py to `https://{0}{1}{2}`, but I can only imagine that this change should be applied in more than one place, hence no PR as this solution is likely to be incomplete.

**Comment by wargio** [comment]
Oh, nice. I'll try to patch it asap

**Comment by wargio** [comment]
fixed via https://github.com/wargio/plugin.video.southpark_unofficial/commit/e57d2ce4899de1724472d7204490b3a5c469c41f.

i'm waiting to have the helix pr to be merged to be distributed globally https://github.com/xbmc/repo-plugins/pull/2450

**Comment by wargio** [comment]
merged on xbmc repo.
