### ISSUE TITLE
[DE] Random Episodes don't work anymore

### ISSUE THREAD

**Issue by SkyBird1980** [wargio/plugin.video.southpark_unofficial#20]
Kodi will not show a Random Episode.
Kodi log says:  HTTP Error 404, not found.

```
2019-10-13 20:15:06.484 T:2772   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
 - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'urllib2.HTTPError'>
Error Contents: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "C:\Users\Stefan\AppData\Roaming\Kodi\addons\plugin.video.southpark_unofficial\default.py", line 9, in <module>
    plugin.handle()
  File "C:\Users\Stefan\AppData\Roaming\Kodi\addons\plugin.video.southpark_unofficial\southpark.py", line 639, in handle
    self.create_random()
  File "C:\Users\Stefan\AppData\Roaming\Kodi\addons\plugin.video.southpark_unofficial\southpark.py", line 386, in create_random
    body = _http_get(self.helper.random_episode("random"))
  File "C:\Users\Stefan\AppData\Roaming\Kodi\addons\plugin.video.southpark_unofficial\southpark.py", line 91, in _http_get
    response = urlopen(req)
  File "C:\Program Files\Kodi\system\python\Lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files\Kodi\system\python\Lib\urllib2.py", line 435, in open
    response = meth(req, response)
  File "C:\Program Files\Kodi\system\python\Lib\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Program Files\Kodi\system\python\Lib\urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "C:\Program Files\Kodi\system\python\Lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\Program Files\Kodi\system\python\Lib\urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 404: Not Found
-->End of Python script error report<--
```

Same on Kodi 18.4 and Kodi 19 Beta.
Language is set to DE / DE.

**Comment by wargio** [comment]
Thanks for reporting this. i'll patch it asap.

**Comment by wargio** [comment]
Fix: https://github.com/xbmc/repo-plugins/pull/2564

**Comment by wargio** [comment]
fixed and closed
