### ISSUE TITLE
Doesn't work with Libreelec Milhouse builds >20191012 (=Python3)

### ISSUE THREAD

**Issue by Message0815** [wargio/plugin.video.southpark_unofficial#23]
kodi.log

`2019-12-29 23:54:07.009 T:1158   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'AttributeError'>
                                            Error Contents: 'str' object has no attribute 'decode'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.southpark_unofficial/default.py", line 9, in <module>
                                                plugin.handle()
                                              File "/storage/.kodi/addons/plugin.video.southpark_unofficial/southpark.py", line 636, in handle
                                                self.create_episodes(kodi.PARAM_URL)
                                              File "/storage/.kodi/addons/plugin.video.southpark_unofficial/southpark.py", line 427, in create_episodes
                                                jsonrsp = jsonrsp.decode('utf-8')
                                            AttributeError: 'str' object has no attribute 'decode'
                                            -->End of Python script error report<--
2019-12-29 23:54:07.984 T:1158 WARNING: CPythonInvoker(24, /storage/.kodi/addons/plugin.video.southpark_unofficial/default.py): the python script "/storage/.kodi/addons/plugin.video.southpark_unofficial/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE
2019-12-29 23:54:08.003 T:1160   ERROR: GetDirectory - Error getting plugin://plugin.video.southpark_unofficial/?mode=sp%3aseason&url=4
2019-12-29 23:54:08.006 T:540   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.southpark_unofficial/?mode=sp%3aseason&url=4) failed`

**Comment by wargio** [comment]
Damn. py3 strikes.
