### ISSUE TITLE
Not compatible with Kodi 19 (Matrix)

### ISSUE THREAD

**Issue by BugDeliverer** [wargio/plugin.video.southpark_unofficial#24]
Kodi 19 (Matrix) has dropped Python v2.x (EOL) and uses Python 3.
The plugin, even the dev branch, requires Python 2 as a dependency.

**Comment by wargio** [comment]
is this a bot?
anyway the plugin is py3 ready. the only requirement is in the config.

**Comment by BugDeliverer** [comment]
Nope, I am a real person.
So, if this plugin is ready for py3 there must be another issue with Kodi 19.
I'm using Libreelec Matrix dev build. The plugin stopped working at build 20200301. Changelog:
http://forum.kodi.tv/showthread.php?tid=343068&pid=2928509
> Build Highlights:
    [python] set abi to 3.0.0
        Quote:
            this change will make sure all installed py2 addons will get disabled when a user upgrades to kodi v19.
            this change will prevent a user from installing (repo and/or zip) py2 addons in kodi.

**Comment by wargio** [comment]
ok. let me do a change with the dev branch and you can try it

**Comment by wargio** [comment]
https://github.com/wargio/plugin.video.southpark_unofficial/archive/dev.zip try this version.

**Comment by BugDeliverer** [comment]
Unfortionately it doesn't work. Now the dependency Python 3.6 can't be fullfilled.
I'm on latest Libreelec Milhouse Dev Build (20200511).

**Comment by wargio** [comment]
what is the python version there?

**Comment by BugDeliverer** [comment]
Latest dev build uses Python 3.7.5
> LibreELEC (Milhouse): devel-20200519212340-#0519-g68af82c (RPi2.arm)
IntegrationPi:~ # python
Python 3.7.6 (default, Apr  9 2020, 06:38:39)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by wargio** [comment]
Ok, i've investigated on this by checking what the other plugins were doing

I've updated the plugin to the same py3 version as the others: https://github.com/wargio/plugin.video.southpark_unofficial/archive/dev.zip

**Comment by BugDeliverer** [comment]
The good news: Installation works!!! :)
The bad news: The plugin has no icon and selecting a season or a random episode doesn't work. Log:

> 2020-05-23 21:29:13.857 T:645      INFO <general>: JSONRPC Server: New connection added
2020-05-23 21:29:16.114 T:604      INFO <general>: CActiveAESink::OpenSink - initialize sink
2020-05-23 21:29:16.151 T:604      INFO <general>: PulseAudio: Opened device Default in pcm mode with Buffersize 150 ms Periodsize 50 ms
2020-05-23 21:29:21.779 T:550     ERROR <general>: Control 55 in window 10025 has been asked to focus, but it can't
2020-05-23 21:29:25.160 T:862      INFO <general>: initializing python engine.
2020-05-23 21:29:25.808 T:862     ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'str' object has no attribute 'decode'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.southpark_unofficial/default.py", line 9, in <module>
                                                       plugin.handle()
                                                     File "/storage/.kodi/addons/plugin.video.southpark_unofficial/southpark.py", line 651, in handle
                                                       self.create_episodes(kodi.PARAM_URL)
                                                     File "/storage/.kodi/addons/plugin.video.southpark_unofficial/southpark.py", line 440, in create_episodes
                                                       jsonrsp = jsonrsp.decode('utf-8')
                                                   AttributeError: 'str' object has no attribute 'decode'
                                                   -->End of Python script error report<--

2020-05-23 21:29:26.427 T:862   WARNING <general>: CPythonInvoker(13, /storage/.kodi/addons/plugin.video.southpark_unofficial/default.py): the python script "/storage/.kodi/addons/plugin.video.southpark_unofficial/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE
2020-05-23 21:29:26.428 T:862      INFO <general>: Python interpreter stopped
2020-05-23 21:29:26.447 T:861     ERROR <general>: GetDirectory - Error getting plugin://plugin.video.southpark_unofficial/?mode=sp%3aseason&url=1
2020-05-23 21:29:26.448 T:550     ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.southpark_unofficial/?mode=sp%3aseason&url=1) failed
2020-05-23 21:29:29.710 T:645      INFO <general>: JSONRPC Server: Disconnection detected

**Comment by wargio** [comment]
can you try again? i made a few changes. tell me if you see the icon also

**Comment by BugDeliverer** [comment]
Installation fails with no message on gui.
Log:
> 2020-05-23 22:51:50.501 T:645      INFO <general>: JSONRPC Server: New connection added
2020-05-23 22:51:51.703 T:550      INFO <general>: Loading skin file: DialogContextMenu.xml, load type: KEEP_IN_MEMORY
2020-05-23 22:51:58.106 T:550      INFO <general>: Loading skin file: DialogAddonInfo.xml, load type: KEEP_IN_MEMORY
2020-05-23 22:52:03.298 T:550      INFO <general>: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
2020-05-23 22:52:09.496 T:550   WARNING <general>: CGUIMediaWindow::OnMessage - updating in progress
2020-05-23 22:52:17.033 T:550      INFO <general>: Loading skin file: FileBrowser.xml, load type: KEEP_IN_MEMORY
2020-05-23 22:52:22.512 T:550     ERROR <general>: CAddonInfoBuilder::Generate: Unable to load 'zip://%2fstorage%2fdev.zip/plugin.video.southpark_unofficial-dev/addon.xml', Line 22
                                                   Failed to read Element name
>2020-05-23 22:52:40.079 T:645      INFO <general>: JSONRPC Server: Disconnection detected

**Comment by wargio** [comment]
try again o/

**Comment by BugDeliverer** [comment]
Installation and icon works now.
Selecting a season still throws an error:
Log:
> 2020-05-26 22:11:08.125 T:1560     INFO <general>: initializing python engine.
2020-05-26 22:11:08.822 T:1560    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'str' object has no attribute 'decode'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.southpark_unofficial/default.py", line 9, in <module>
                                                       plugin.handle()
                                                     File "/storage/.kodi/addons/plugin.video.southpark_unofficial/southpark.py", line 648, in handle
                                                       self.create_episodes(kodi.PARAM_URL)
                                                     File "/storage/.kodi/addons/plugin.video.southpark_unofficial/southpark.py", line 437, in create_episodes
                                                       jsonrsp = jsonrsp.decode('utf-8')
                                                   AttributeError: 'str' object has no attribute 'decode'
                                                   -->End of Python script error report<--

> 2020-05-26 22:11:09.433 T:1560  WARNING <general>: CPythonInvoker(13, /storage/.kodi/addons/plugin.video.southpark_unofficial/default.py): the python script "/storage/.kodi/addons/plugin.video.southpark_unofficial/default.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE
> 2020-05-26 22:11:09.433 T:1560     INFO <general>: Python interpreter stopped
> 2020-05-26 22:11:09.451 T:1559    ERROR <general>: GetDirectory - Error getting plugin://plugin.video.southpark_unofficial/?mode=sp%3aseason&url=2
> 2020-05-26 22:11:09.453 T:548     ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.southpark_unofficial/?mode=sp%3aseason&url=2) failed

**Comment by wargio** [comment]
> = jsonrsp.decode('utf-8')
> AttributeError: 'str' object has no attribute 'decode'
> -->End of Python script error report<--

these logs are weird. `jsonrsp = jsonrsp.decode('utf-8')` was removed with this commit https://github.com/wargio/plugin.video.southpark_unofficial/commit/56278cb8cb4351bac7f623c94314b06fcb91ade1

**Comment by wargio** [comment]
be sure to uninstall and re-download the lastest version of the zip

**Comment by BugDeliverer** [comment]
Thats exactly what I did.. Repeated it now but error stays the same on selecting a season. But only when I switch language (and location) to DE - languages EN or ES are working fine.

**Comment by BugDeliverer** [comment]
Please, have a look at southpark.py, lines 435-437.
I guess thats the problem.

**Comment by wargio** [comment]
you are absolutely right. i missed it and i got confused by the other line. Thanks :D
Try once more !

**Comment by BugDeliverer** [comment]
Wohoo! Finally it's working on Libreelec with KODI19. Thank you so much for your work and patience.
Hope the matrix branch will soon find it's way to the KODI repo.    ;)

**Comment by wargio** [comment]
Thank you for your patience. i'll push an update only for Matrix asap.

**Comment by wargio** [comment]
https://github.com/xbmc/repo-plugins/pull/2957
Sorry for the delay

**Comment by wargio** [comment]
merged on official repository.
