### ISSUE TITLE
Can't watch any episode

### ISSUE THREAD

**Issue by UnderGames420** [wargio/plugin.video.southpark_unofficial#33]
![20201009_212738](https://user-images.githubusercontent.com/73075085/96375465-d3650b00-1181-11eb-9e4e-c062c3d97f58.jpg)
I have a problem that all episodes but the pandemic special don't play. I can browse the seasons, but when I choose an episodes it loads but then does nothing.
I wasn't able to upload the log but I did take a picture of it which is attached.

**Comment by wargio** [comment]
can you tell me these details?

- Country you live
- Settings
- Addon Version

**Comment by UnderGames420** [comment]
I live in Israel(the us website is working here, tried it on my browser), Geo Location: North America[EN](Also tried UK and DE), with CC. It used to work...

**Comment by UnderGames420** [comment]
Welp just saw you added a "clear cache" button and now everything seems to work.... I'll let you know if the problem returns

**Comment by wargio** [comment]
does or does not work? if solved please close the issue.

**Comment by UnderGames420** [comment]
No, it doesn't. 
Yesterday episodes from seasons 9 to 24 worked(seasons 1-8 didn't), but today only specific seasons like 21 and 19 actually play(I did clear the cache)

**Comment by wargio** [comment]
> No, it doesn't.
> Yesterday episodes from seasons 9 to 24 worked(seasons 1-8 didn't), but today only specific seasons like 21 and 19 actually play(I did clear the cache)

try with the european streams.

**Comment by Elzama** [comment]
I have the same issue.  I posted a while ago, clearing cache fixed 1 episode, it stopped working after that :/ 
Only the latest episode plays.

**Comment by beachmiles** [comment]
English north america here on 0.6.3 on kodi.
The episode seems to generally start ok but generally after the intro commercial the video freezes at the the end of the commercial but the south park episode starts so I can then manually switch the video stream from the (h264, 448x252)(1/2) stream to the
(h264, 1920x1080)(2/2) stream.
After I switch the stream the episode stream crashes and if i restart the episode and play from beginning the intro commercial plays and then the south park episode starts playing correctly.

Unfortunatly when the next commercial comes up the south park video freezes and the commercial audio starts but then the south park video doesn't start again and no matter what I do I can't get the video to continue.

Smaller bug is the fast forward and rewind generally kills the stream.

**Comment by wargio** [comment]
unfortunately i can't fix that bug, because is kodi related. what i could do is removing ads, but requires me parsing m3u8

**Comment by beachmiles** [comment]
If you could remove the ads that would be amazing and may fix the problem in kodi.

**Comment by thenextdon13** [comment]
Hello-
I think this may be related to this bug
I live in the united states.  Plugin version 0.6.3 
Linux kodiarch 5.9.8-arch1-1 #1 SMP PREEMPT Tue, 10 Nov 2020 22:44:11 +0000 x86_64 GNU/Linux
\<addon id="plugin.video.southpark_unofficial" name="South Park" version="0.6.3" provider-name="Deroad"\>



my available geolocations are
southpark.py:           self.geolocation = ["en", "es", "de", "se", "eu"]


es, en, and eu  do not work for most episodes i've tried (pandemic special worked on en but none of the misc other's i've tried do);  

The kodi log has this for, example, S19 E08:
`2020-11-22 13:50:56.960 T:139718582830656   ERROR: [sp.addon] expected string or buffer
2020-11-22 13:50:58.898 T:139719938022080  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.southpark_unofficial/?mode=sp:play&season=19&episode=8
2020-11-22 13:50:59.057 T:139717147874880  NOTICE: Creating InputStream
2020-11-22 13:50:59.245 T:139717147874880  NOTICE: Creating Demuxer
2020-11-22 13:50:59.246 T:139717147874880  NOTICE: Opening stream: 1001 source: 256
2020-11-22 13:50:59.462 T:139717147874880  NOTICE: Whitelist search for: width: 1280, height: 720, fps: 23.976, 3D: false
2020-11-22 13:50:59.462 T:139717147874880  NOTICE: Display resolution ADJUST : HDMI1: 1920x1080 @ 23.98Hz (16) (weight: 0.000)
2020-11-22 13:50:59.468 T:139717147874880 WARNING: OpenStream - Unsupported stream 1001. Stream disabled.
2020-11-22 13:50:59.469 T:139717147874880  NOTICE: Opening stream: 1002 source: 256
2020-11-22 13:50:59.469 T:139717147874880  NOTICE: Finding audio codec for: 86018
2020-11-22 13:50:59.471 T:139717147874880  NOTICE: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder aac
2020-11-22 13:50:59.471 T:139717147874880  NOTICE: Creating audio thread
2020-11-22 13:50:59.472 T:139717173057088  NOTICE: running thread: CVideoPlayerAudio::Process()
2020-11-22 13:50:59.472 T:139717147874880  NOTICE: CVideoPlayer::OnExit()
2020-11-22 13:50:59.473 T:139717147874880  NOTICE: VideoPlayer: eof, waiting for queues to empty
2020-11-22 13:50:59.473 T:139717147874880  NOTICE: Closing stream player 1
2020-11-22 13:50:59.473 T:139717147874880  NOTICE: Waiting for audio thread to exit
2020-11-22 13:50:59.482 T:139717173057088  NOTICE: thread end: CVideoPlayerAudio::OnExit()
2020-11-22 13:50:59.482 T:139717147874880  NOTICE: Closing audio device
2020-11-22 13:50:59.483 T:139717147874880  NOTICE: Deleting audio codec
2020-11-22 13:50:59.510 T:139719938022080  NOTICE: CVideoPlayer::CloseFile()
2020-11-22 13:50:59.517 T:139719938022080  NOTICE: VideoPlayer: waiting for threads to exit
2020-11-22 13:50:59.517 T:139719938022080  NOTICE: VideoPlayer: finished waiting
2020-11-22 13:50:59.517 T:139719938022080  NOTICE: CVideoPlayer::CloseFile()
2020-11-22 13:50:59.517 T:139719938022080  NOTICE: VideoPlayer: waiting for threads to exit
2020-11-22 13:50:59.517 T:139719938022080  NOTICE: VideoPlayer: finished waiting
`


de and se do work, and the log looks like this
`2020-11-22 13:55:31.863 T:139718582830656   ERROR: [sp.addon] expected string or buffer
2020-11-22 13:55:33.463 T:139719938022080  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.southpark_unofficial/?mode=sp:play&season=19&episode=8
2020-11-22 13:55:33.625 T:139717114304064  NOTICE: Creating InputStream
2020-11-22 13:55:33.827 T:139717114304064  NOTICE: Creating Demuxer
2020-11-22 13:55:33.827 T:139717114304064  NOTICE: Opening stream: 1001 source: 256
2020-11-22 13:55:34.170 T:139717114304064  NOTICE: Whitelist search for: width: 1280, height: 720, fps: 23.976, 3D: false
2020-11-22 13:55:34.171 T:139717114304064  NOTICE: Display resolution ADJUST : HDMI1: 1920x1080 @ 23.98Hz (16) (weight: 0.000)
2020-11-22 13:55:34.202 T:139717114304064  NOTICE: Creating video codec with codec id: 27
2020-11-22 13:55:34.202 T:139717114304064  NOTICE: CDVDVideoCodecFFmpeg::Open() Using codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
2020-11-22 13:55:34.203 T:139717114304064  NOTICE: Creating video thread
2020-11-22 13:55:34.203 T:139717084935744  NOTICE: running thread: video_thread
2020-11-22 13:55:34.203 T:139717114304064  NOTICE: Opening stream: 1002 source: 256
2020-11-22 13:55:34.203 T:139717114304064  NOTICE: Finding audio codec for: 86018
2020-11-22 13:55:34.204 T:139717114304064  NOTICE: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder aac
2020-11-22 13:55:34.204 T:139717114304064  NOTICE: Creating audio thread
2020-11-22 13:55:34.204 T:139717315827264  NOTICE: running thread: CVideoPlayerAudio::Process()
2020-11-22 13:55:34.209 T:139717181445696  NOTICE: COutput::OnStartup: Output Thread created
2020-11-22 13:55:34.215 T:139717315827264  NOTICE: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder aac
2020-11-22 13:55:34.215 T:139717315827264  NOTICE: Creating audio stream (codec id: 86018, channels: 2, sample rate: 48000, no pass-through)
2020-11-22 13:55:34.254 T:139719938022080  NOTICE: GL: Selecting YUV 2 RGB shader
2020-11-22 13:55:34.255 T:139719938022080  NOTICE: GL: NPOT texture support detected
2020-11-22 13:55:34.255 T:139719938022080  NOTICE: GL: Using GL_ARB_pixel_buffer_object
2020-11-22 13:55:34.255 T:139719938022080  NOTICE: Using GL_TEXTURE_2D
2020-11-22 13:55:34.497 T:139719938022080  NOTICE: Whitelist search for: width: 1280, height: 720, fps: 23.976, 3D: false
2020-11-22 13:55:34.497 T:139719938022080  NOTICE: Display resolution ADJUST : HDMI1: 1920x1080 @ 23.98Hz (16) (weight: 0.000)
2020-11-22 13:55:34.499 T:139719938022080  NOTICE: GL: Selecting YUV 2 RGB shader
2020-11-22 13:55:34.500 T:139719938022080  NOTICE: GL: NPOT texture support detected
2020-11-22 13:55:34.500 T:139719938022080  NOTICE: GL: Using GL_ARB_pixel_buffer_object
2020-11-22 13:55:34.745 T:139717084935744  NOTICE: CDVDVideoCodecFFmpeg::CDropControl: calculated diff time: 41708
`

Pandemic special fails on es, with
`2020-11-22 13:57:15.628 T:139717181445696   ERROR: GetDirectory - Error getting plugin://plugin.video.southpark_unofficial/?mode=sp%3aseason&season=24
2020-11-22 13:57:15.636 T:139719938022080   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.southpark_unofficial/?mode=sp%3aseason&season=24) failed
2020-11-22 13:57:19.186 T:139717361456704   ERROR: [sp.addon] expected string or buffer
2020-11-22 13:57:23.868 T:139717361456704   ERROR: Previous line repeats 1 times.
2020-11-22 13:57:23.868 T:139717361456704   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/home/kodiuser/.kodi/addons/plugin.video.southpark_unofficial/default.py", line 9, in <module>
                                                plugin.handle()
                                              File "/home/kodiuser/.kodi/addons/plugin.video.southpark_unofficial/southpark.py", line 473, in handle
                                                self.create_episodes(kodi.PARAM_SEASON)
                                              File "/home/kodiuser/.kodi/addons/plugin.video.southpark_unofficial/southpark.py", line 343, in create_episodes
                                                for episode in self.data.seasons[int(season) - 1]:
                                            IndexError: list index out of range
                                            -->End of Python script error report<--
2020-11-22 13:57:23.917 T:139717181445696   ERROR: GetDirectory - Error getting plugin://plugin.video.southpark_unofficial/?mode=sp%3aseason&season=24
2020-11-22 13:57:23.936 T:139719938022080   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.southpark_unofficial/?mode=sp%3aseason&season=24) failed
`


Pandemic special works on en, with
`2020-11-22 13:58:56.050 T:139717324215872   ERROR: [sp.addon] expected string or buffer
2020-11-22 13:58:58.499 T:139719938022080  NOTICE: VideoPlayer::OpenFile: plugin://plugin.video.southpark_unofficial/?mode=sp:play&season=24&episode=1
2020-11-22 13:58:58.680 T:139717084935744  NOTICE: Creating InputStream
2020-11-22 13:58:58.876 T:139717084935744  NOTICE: Creating Demuxer
2020-11-22 13:58:58.877 T:139717084935744  NOTICE: Opening stream: 1001 source: 256
2020-11-22 13:58:59.346 T:139717084935744  NOTICE: Whitelist search for: width: 1280, height: 720, fps: 23.976, 3D: false
2020-11-22 13:58:59.347 T:139717084935744  NOTICE: Display resolution ADJUST : HDMI1: 1920x1080 @ 23.98Hz (16) (weight: 0.000)
2020-11-22 13:58:59.370 T:139717084935744  NOTICE: Creating video codec with codec id: 27
2020-11-22 13:58:59.370 T:139717084935744  NOTICE: CDVDVideoCodecFFmpeg::Open() Using codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
2020-11-22 13:58:59.371 T:139717084935744  NOTICE: Creating video thread
2020-11-22 13:58:59.373 T:139717084935744  NOTICE: Opening stream: 1002 source: 256
2020-11-22 13:58:59.373 T:139717315823168  NOTICE: running thread: video_thread
2020-11-22 13:58:59.374 T:139717084935744  NOTICE: Finding audio codec for: 86018
2020-11-22 13:58:59.375 T:139717084935744  NOTICE: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder aac
`

**Comment by wargio** [comment]
@thenextdon13 yes it is related to the same issue as the others. let's say that US is special

**Comment by Hedronmx** [comment]
Can confirm, only German and Sweden works
