### ISSUE TITLE
Problem with non ASCII Characters in Episode Titles

### ISSUE THREAD

**Issue by Markusnator2012** [wargio/plugin.video.southpark_unofficial#34]
When trying to play the Episode **Pandemic 2 – The Startling** (S12E11), the ASCII codec isn't able to decode the EN Dash (\u2013, '–') in the Title and the episode can't be played because of this.

**Kodi Version**: Kodi 18.8
**Addon Version**: 0.6.3
**Geo Location**: Sweden

````
2020-10-29 15:54:53.809 T:3548   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeEncodeError'>
                                            Error Contents: 'ascii' codec can't encode character u'\u2013' in position 11: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "C:\Users\Markus\AppData\Roaming\Kodi\addons\plugin.video.southpark_unofficial\default.py", line 9, in <module>
                                                plugin.handle()
                                              File "C:\Users\Markus\AppData\Roaming\Kodi\addons\plugin.video.southpark_unofficial\southpark.py", line 476, in handle
                                                self.play_episode(kodi.PARAM_SEASON, kodi.PARAM_EPISODE)
                                              File "C:\Users\Markus\AppData\Roaming\Kodi\addons\plugin.video.southpark_unofficial\southpark.py", line 440, in play_episode
                                                title = "{title} ({i}/{n})".format(title=title, i=(i + 1), n=parts)
                                            UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 11: ordinal not in range(128)
                                            -->End of Python script error report<--
````

**Comment by wargio** [comment]
Fixed. please remove the cache (there is an option in the settings) ad let me know.

**Comment by Markusnator2012** [comment]
Thanks! Its working again.

**Comment by Markusnator2012** [comment]
The Character \u2026 (Ellipsis, '…') in the title of the Episode **About Last Night…** (S12E12) is causing the same Issue.

**Comment by wargio** [comment]
fixed again. (i found 2 hits with the ellipsis)

**Comment by Markusnator2012** [comment]
Thanks again! Its working now.
